### ISSUE TITLE
kart import crash

### ISSUE THREAD

**Issue by vbjay** [koordinates/kart#567] opened 2022-03-02 06:05 UTC
**Describe the bug**

→ If you're using the QGIS plugin, please file your issue at the [plugin project](https://github.com/koordinates/kart-qgis-plugin/issues/new/choose).

**To Reproduce**
Steps to reproduce the behaviour:
1. Init repo and import a geopakage
2. make changes 
3. commit
4. run  a command like the following to import changes pulled from an updated generated geopackage file
    ```bash
    kart import "E:\Apps\Git\RoadNetCloud-Repo\Blue Rhino.gpkg" -a --replace-existing
    ```
  Tried the following and then rerunning import

```bash
    kart create-workingcopy --delete-existing
    kart gc
    kart reset --discard-changes
```
[kart.log](https://github.com/koordinates/kart/files/8166972/kart.log)

**Expected behaviour**
What did you expect to happen?
clean import
**Output**
Add the output you're seeing to help explain your problem.
```
...
Importing 2 features from Blue Rhino.gpkg:377040-Multiple Standard Routes to 377
040-Multiple Standard Routes/ ...
Added 2 Features to index in 0.0s
Overall rate: 65 features/s)
Closed in 0s
Importing 16 features from Blue Rhino.gpkg:377040-Standard Routes to 377040-Stan
dard Routes/ ...

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
fatal:fatal: stream ends early
 EOF in data (2695 bytes remaining)
ffast-import: dumping crash report to fast_import_crash_13356

E:\Apps\Git\GisData\cells\Data>ast-import: dumping crash report to fast_import_c
rash_14468
```
[fast_import_crash_13356.txt](https://github.com/koordinates/kart/files/8166879/fast_import_crash_13356.txt)
[fast_import_crash_14468.txt](https://github.com/koordinates/kart/files/8166887/fast_import_crash_14468.txt)

**Version Info **
 - OS: Microsoft Windows [Version 6.3.9600]
 - Version: [from `kart version`]
Kart v0.11.0, Copyright (c) Kart Contributors
» GDAL v3.3.2; PROJ v8.1.1
» PyGit2 v1.7.0; Libgit2 v1.3.0; Git v2.34.0.windows.1.13.g93318cbc8d
» SQLAlchemy v1.4.29; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.0; Libpq v11.0.9
» SpatialIndex v1.9.3

I do have git installed and that info is
git version 2.35.1.windows.2

**Comment by olsen232** [comment] 2022-03-03 03:05
I tried to reproduce - I found a random GPKG and:
1. Imported it into a Kart repo
2. Modified the resulting dataset in the Kart repo
3. Committed the changes
4a. Modified the original GPKG, and reimported it with --replace-existing.
4b. Ran the following commands: `kart create-workingcopy --delete-existing`, `kart gc`, `kart reset --discard-changes`

Everything seemed to work as expected. I tried reimporting the same GPKG again (which doesn't work as it results in no changes) but this seemed to work as expected too. Perhaps it depends on the GPKG - can you send me a GPKG with which you can reproduce it?

**Comment by vbjay** [comment] 2022-03-03 03:39
I'll try. I can't send what I'm importing from but I can try to create a
replication sample.

**Comment by craigds** [comment] 2022-03-15 23:16
@vbjay were you able to find any more information about this?


my interpretation of the fast-improt crash logs is that the git process didn't crash but the kart process that was feeding it data did crash (so git aborted because it ran out of commands to process). If that's the case it seems like we're either missing a stack trace from kart, or kart was hard-killed by the operating system (perhaps out-of-memory or similar so that no stack trace appeared)

A minimal sample would be ideal as it's hard to know what caused this from the info we have. If that's not possible, I would suggest trying:

 - rename the dataset during the import, so that it doesn't start with a number and doesn't contain spaces: `kart import "Blue Rhino.gpkg" "377040-Multiple Standard Routes:multiple_standard_routes"`  (it _should_ work as-is but I have a hunch it might not)
 - try it in a Linux or Mac environment if possible, in case there's a difference in behaviour that's helpful for diagnosing the issue.

**Comment by vbjay** [comment] 2022-03-16 21:25
I'mbeen swamped lately. Trying to find time to get a minimal sample that isn't corporate data.

**Closed** 2024-07-01 22:18 UTC
