### ISSUE TITLE
init/import: problems when importing from PG, error in ORG type LineString and others schemas than public

### ISSUE THREAD

**Issue by diogooliveira-dsg** [koordinates/kart#434] opened 2021-06-01 14:52 UTC
I'm having some problems testing kart in Postgres/PostGIS.

First i tried to do the init --import command, but i recivied the "OGR type=StringList" error:

> kart init --import postgresql://user:password@localhost/db_master
> Initialized empty Git repository in /home/user/repo_db_master/.kart/
> Error: Unsupported column type for import: OGR type=StringList

So I decided to init without any parameter and then do the import, but now seems that the import does not have the ability to handle more schemas then public:

> kart import postgresql://user:password@localhost/db_master schema1.table1
> Starting git-fast-import...
> Importing 4 features from postgresql://user:password@localhost/db_master:schema1.table1 to schema1.table1/ ...
> Traceback (most recent call last):
>   File "site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
>   File "site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
> psycopg2.errors.UndefinedTable: relation "schema1.table1" does not exist
> LINE 1: ...a2a1ad90_1" CURSOR WITHOUT HOLD FOR SELECT * FROM "schema1.tabl...
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "kart_cli.py", line 4, in <module>
>   File "site-packages/kart-0.9.0-py3.7.egg/sno/cli.py", line 333, in entrypoint
>   File "site-packages/click/core.py", line 829, in _call_
>   File "site-packages/click/core.py", line 782, in main
>   File "site-packages/kart-0.9.0-py3.7.egg/sno/cli.py", line 157, in invoke
>   File "site-packages/click/core.py", line 1259, in invoke
>   File "site-packages/click/core.py", line 1066, in invoke
>   File "site-packages/click/core.py", line 610, in invoke
>   File "site-packages/click/decorators.py", line 21, in new_func
>   File "site-packages/kart-0.9.0-py3.7.egg/sno/init.py", line 342, in import_
>   File "site-packages/kart-0.9.0-py3.7.egg/sno/fast_import.py", line 393, in fast_import_tables
>   File "site-packages/kart-0.9.0-py3.7.egg/sno/dataset2.py", line 358, in import_iter_feature_blobs
>   File "site-packages/kart-0.9.0-py3.7.egg/sno/ogr_import_source.py", line 656, in features
>   File "site-packages/sqlalchemy/engine/base.py", line 1190, in execute
>   File "site-packages/sqlalchemy/engine/base.py", line 1491, in _exec_driver_sql
>   File "site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
>   File "site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
>   File "site-packages/sqlalchemy/util/compat.py", line 211, in raise_
>   File "site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
>   File "site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
> sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "schema1.table1" does not exist
> LINE 1: ...a2a1ad90_1" CURSOR WITHOUT HOLD FOR SELECT * FROM "schema1.tabl...
> 
> [SQL: SELECT * FROM "schema1.table1";]
> (Background on this error at: http://sqlalche.me/e/14/f405)
> [5818] Failed to execute script kart_cli
> fatal: stream ends early
> fatal: stream ends early
> fast-import: dumping crash report to fast_import_crash_5835
> fast-import: dumping crash report to fast_import_crash_5829
> fatal: stream ends early
> fatal: stream ends early
> fast-import: dumping crash report to fast_import_crash_5826
> fast-import: dumping crash report to fast_import_crash_5832

for test purposes only, I created a new db and move the table to public schema. I received the same error when trying the init --import, but after no specification init, when trying import, it seems that it works:

> kart import postgresql://user:password@localhost/db_master table1
> Starting git-fast-import...
> Importing 4 features from postgresql://user:password@localhost/db_master:table1 to tabel1/ ...
> Added 4 Features to index in 0.0s
> Overall rate: 348 features/s)
> Closed in 0s
> Joining 4 parallel-imported trees...
> Joined trees in 0s
> Creating working copy at repo_teste.gpkg ...

Kart v0.9.0, Copyright (c) Kart Contributors
» GDAL v3.2.0; PROJ v6.3.0
» PyGit2 v1.3.0; Libgit2 v1.1.0; Git v2.29.2
» SQLAlchemy v1.4.4; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.0; Libpq v10.0.12
» SpatialIndex v1.9.3

**Comment by rcoup** [comment] 2021-06-01 15:00
> First i tried to do the init --import command, but i recivied the "OGR type=StringList" error:

What's the schema of `table1` look like? (in `psql`: `\pset pager off \d table1`). Feel free to change the column names if they're sensitive, I'm more interested in the data types.

@olsen232 can comment on the second issue, looks like maybe the schema isn't being split off correctly somewhere. It definitely _should_ work 😄

**Comment by diogooliveira-dsg** [comment] 2021-06-01 15:13
It seems that the problem is in the geom cloumn

> Table "schema1.tabel1"
>        Column        |             Type             | Collation | Nullable |                     Default                     
> ---------------------+------------------------------+-----------+----------+-------------------------------------------------
>  id                  | integer                      |           | not null | nextval('table1_id_seq'::regclass)
>  name                | character varying(255)       |           |          | 
>  type                | smallint                     |           | not null | 999
>  mat_constr          | smallint                     |           | not null | 999
>  obs                 | character varying(255)       |           |          | 
>  ctr_id              | uuid                         |           |          | 
>  geom                | geometry(MultiPolygon,31982) |           |          | 
> Indexes:
>     "table1_pk" PRIMARY KEY, btree (id) WITH (fillfactor='80')
>     "table1_geom" gist (geom)
> Check constraints:
>     "table1_mat_constr_check" CHECK (mat_constr = ANY (ARRAY[0::smallint, 1::smallint, 2::smallint, 3::smallint, 4::smallint, 5::smallint, 97::smallint, 98::smallint, 999::smallint]))
>     "table1_type_check" CHECK (type = ANY (ARRAY[0::smallint, 1::smallint, 2::smallint, 101::smallint, 102::smallint, 103::smallint, 104::smallint, 201::smallint, 301::smallint, 302::smallint, 303::smallint, 395::smallint, 398::smallint, 403::smallint, 405::smallint, 406::smallint, 407::smallint, 498::smallint, 516::smallint, 517::smallint, 518::smallint, 519::smallint, 520::smallint, 521::smallint, 522::smallint, 523::smallint, 524::smallint, 525::smallint, 595::smallint, 601::smallint, 602::smallint, 603::smallint, 604::smallint, 605::smallint, 606::smallint, 607::smallint, 698::smallint, 709::smallint, 710::smallint, 711::smallint, 712::smallint, 713::smallint, 798::smallint, 801::smallint, 802::smallint, 803::smallint, 804::smallint, 805::smallint, 806::smallint, 807::smallint, 808::smallint, 898::smallint, 903::smallint, 904::smallint, 905::smallint, 906::smallint, 907::smallint, 998::smallint, 1015::smallint, 1016::smallint, 1017::smallint, 1018::smallint, 1019::smallint, 1020::smallint, 1021::smallint, 1022::smallint, 1023::smallint, 1024::smallint, 1025::smallint, 1026::smallint, 1027::smallint, 1028::smallint, 1029::smallint, 1030::smallint, 1031::smallint, 1032::smallint, 1033::smallint, 1034::smallint, 1035::smallint, 1036::smallint, 1037::smallint, 1045::smallint, 1098::smallint, 1110::smallint, 1111::smallint, 1113::smallint, 1114::smallint, 1198::smallint, 1212::smallint, 1213::smallint, 1214::smallint, 1215::smallint, 1216::smallint, 1217::smallint, 1218::smallint, 1298::smallint, 1301::smallint, 1302::smallint, 1303::smallint, 1304::smallint, 1305::smallint, 1306::smallint, 1307::smallint, 1308::smallint, 1309::smallint, 1322::smallint, 1398::smallint, 1401::smallint, 1501::smallint, 1712::smallint, 1717::smallint, 1718::smallint, 1719::smallint, 1798::smallint, 1820::smallint, 1821::smallint, 1910::smallint, 1911::smallint, 1995::smallint, 2025::smallint, 2026::smallint, 2027::smallint, 2028::smallint, 2029::smallint, 2030::smallint, 2031::smallint, 2132::smallint, 2133::smallint, 2195::smallint, 2208::smallint, 2209::smallint, 2210::smallint, 2212::smallint, 2213::smallint, 2214::smallint, 2298::smallint, 2316::smallint, 2317::smallint, 2318::smallint, 2319::smallint, 2320::smallint, 2398::smallint, 2426::smallint, 2427::smallint, 2428::smallint, 2429::smallint, 2498::smallint, 2526::smallint, 2527::smallint, 2533::smallint, 2534::smallint, 2535::smallint, 2536::smallint, 2598::smallint, 2601::smallint, 2701::smallint, 999::smallint]))
> Foreign-key constraints:
>     "table1_mat_constr_fk" FOREIGN KEY (mat_constr) REFERENCES mat_constr(code) MATCH FULL
>     "table1_type_fk" FOREIGN KEY (type) REFERENCES type_edf(code) MATCH FULL
> Triggers:
>     a_explode_geom BEFORE INSERT OR UPDATE ON table1 FOR EACH ROW EXECUTE PROCEDURE explode_geom()

**Comment by craigds** [comment] 2021-06-01 20:38
it seems likely this will have changed in recent master builds, since we no longer use OGR for imports from postgres. If you grab a package from [here](https://github.com/koordinates/kart/actions/runs/894339278) do you see the same behaviour?

**Comment by olsen232** [comment] 2021-06-01 21:58
Yes there is a bug in the OGR-based importer where it wouldn't work if you gave it a combined schema+table to import. Possibly you can work around it if you set the default search path of your database to include the schema that contains the table, so that you don't have to specify the schema. But, I don't know - I never really looked into how the OGR-based importer works unfortunately. The latest builds don't use OGR for import but use sqlalchemy directly. So, all old bugs are probably completely gone and replaced by new bugs.

**Comment by diogooliveira-dsg** [comment] 2021-06-01 22:18
> it seems likely this will have changed in recent master builds, since we no longer use OGR for imports from postgres. If you grab a package from [here](https://github.com/koordinates/kart/actions/runs/894339278) do you see the same behaviour?

The behavior changed but still not working properly. Now I received the error: 

> kart init --import postgresql://user:password@localhost/db_master   
> Initialized empty Git repository in /home/user/repo_db_master/.kart/
> Traceback (most recent call last):
>   File "kart_cli.py", line 4, in <module>
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/cli.py", line 334, in entrypoint
>   File "site-packages/click/core.py", line 829, in __call__
>   File "site-packages/click/core.py", line 782, in main
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/cli.py", line 158, in invoke
>   File "site-packages/click/core.py", line 1259, in invoke
>   File "site-packages/click/core.py", line 1066, in invoke
>   File "site-packages/click/core.py", line 610, in invoke
>   File "site-packages/click/decorators.py", line 21, in new_func
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/init.py", line 463, in init
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/fast_import.py", line 254, in fast_import_tables
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/pk_generation.py", line 86, in wrap_sources_if_needed
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/pk_generation.py", line 86, in <listcomp>
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/pk_generation.py", line 79, in wrap_source_if_needed
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/import_source.py", line 137, in schema
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/import_source.py", line 149, in _init_schema
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy_import_source.py", line 200, in get_meta_item
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy_import_source.py", line 210, in meta_items
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 180, in all_v2_meta_items
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 194, in postgis_to_v2_schema
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 194, in <listcomp>
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 215, in _postgis_to_column_schema
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 227, in _pg_type_to_v2_type
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy/adapter/base.py", line 104, in sql_type_to_v2_type
> ValueError: Unsupported SQL type: UUID
> [5962] Failed to execute script kart_cli

But now, I think the problem is not supporting  UUID type. I tried to change the db construction to  alter data type UUID to text, for test purposes, and continues having problems:
 
> kart init --import postgresql://user:password@localhost/db_master_2            
> Initialized empty Git repository in /home/user/repo_db_master/.kart/
> Traceback (most recent call last):
>   File "kart_cli.py", line 4, in <module>
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/cli.py", line 334, in entrypoint
>   File "site-packages/click/core.py", line 829, in __call__
>   File "site-packages/click/core.py", line 782, in main
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/cli.py", line 158, in invoke
>   File "site-packages/click/core.py", line 1259, in invoke
>   File "site-packages/click/core.py", line 1066, in invoke
>   File "site-packages/click/core.py", line 610, in invoke
>   File "site-packages/click/decorators.py", line 21, in new_func
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/init.py", line 463, in init
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/fast_import.py", line 254, in fast_import_tables
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/pk_generation.py", line 86, in wrap_sources_if_needed
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/pk_generation.py", line 86, in <listcomp>
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/pk_generation.py", line 79, in wrap_source_if_needed
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/import_source.py", line 137, in schema
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/import_source.py", line 149, in _init_schema
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy_import_source.py", line 200, in get_meta_item
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy_import_source.py", line 210, in meta_items
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 180, in all_v2_meta_items
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 194, in postgis_to_v2_schema
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/schema.py", line 210, in __init__
>   File "site-packages/kart-0.9.1.dev0+ci.2306.gitf2dd0bfe-py3.7.egg/kart/schema.py", line 344, in _to_legend
> ValueError: Expected contiguous primaryKeyIndex 1 but only found 0
> [7002] Failed to execute script kart_cli

**Comment by diogooliveira-dsg** [comment] 2021-06-01 22:27
> Yes there is a bug in the OGR-based importer where it wouldn't work if you gave it a combined schema+table to import. Possibly you can work around it if you set the default search path of your database to include the schema that contains the table, so that you don't have to specify the schema. But, I don't know - I never really looked into how the OGR-based importer works unfortunately. The latest builds don't use OGR for import but use sqlalchemy directly. So, all old bugs are probably completely gone and replaced by new bugs.

I have tried this solution using "kart init --import postgresql://user:password@localhost/db_master/schema1" (Kart v0.9.0, not the new one)  but it keeps sending the error, it doesn't realize that it was the schema. And it introduces a new problem because if I have more than one schema, it would be looking at just one schema, ignoring other

**Comment by olsen232** [comment] 2021-06-01 22:42
That UUID's are not supported I can fix easily enough.
The other problem I don't fully understand - Kart thinks there are two primary keys in your table, but has failed to discern which is the first primary key and which is the second.

Can you supply the CREATE TABLE command for your table so I can reproduce, or for an example table that seems to have the same issue if you prefer?

**Comment by olsen232** [comment] 2021-06-02 09:06
Sorry, I see the table schema is already attached above. No need to supply anything further.

Okay there are now two new fixes at master - 
- Postgres UUIDs are now imported as text 
- Fixed a bug where foreign keys were being mixed up with primary keys

You can try them out here:
https://github.com/koordinates/kart/actions/runs/898256260

I can also, if it would help you, make a new version just like 0.9.0 but with the schema problem fixed. However, there is a bit of a limit to how many other problems I can fix in 0.9.0 since I don't have time to dig into how OGR works - the StringList issue is probably already beyond me - so from my point of view, fixing problems in the latest master build is of more long term value.

**Comment by diogooliveira-dsg** [comment] 2021-06-02 15:26
> You can try them out here:
> https://github.com/koordinates/kart/actions/runs/898256260
> 
> I can also, if it would help you, make a new version just like 0.9.0 but with the schema problem fixed. However, there is a bit of a limit to how many other problems I can fix in 0.9.0 since I don't have time to dig into how OGR works - the StringList issue is probably already beyond me - so from my point of view, fixing problems in the latest master build is of more long term value.

I tested the  _Build #2314_ , but now the error mensage is about type:NAME : 

> kart init --import postgresql://user:password@localhost/db_master
> Initialized empty Git repository in /home/user/repo_db_master/.kart/
> Traceback (most recent call last):
>   File "kart_cli.py", line 4, in <module>
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/cli.py", line 334, in entrypoint
>   File "site-packages/click/core.py", line 829, in __call__
>   File "site-packages/click/core.py", line 782, in main
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/cli.py", line 158, in invoke
>   File "site-packages/click/core.py", line 1259, in invoke
>   File "site-packages/click/core.py", line 1066, in invoke
>   File "site-packages/click/core.py", line 610, in invoke
>   File "site-packages/click/decorators.py", line 21, in new_func
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/init.py", line 463, in init
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/fast_import.py", line 254, in fast_import_tables
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/pk_generation.py", line 86, in wrap_sources_if_needed
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/pk_generation.py", line 86, in <listcomp>
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/pk_generation.py", line 79, in wrap_source_if_needed
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/import_source.py", line 137, in schema
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/import_source.py", line 149, in _init_schema
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/sqlalchemy_import_source.py", line 200, in get_meta_item
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/sqlalchemy_import_source.py", line 210, in meta_items
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 189, in all_v2_meta_items
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 203, in postgis_to_v2_schema
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 203, in <listcomp>
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 224, in _postgis_to_column_schema
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/sqlalchemy/adapter/postgis.py", line 236, in _pg_type_to_v2_type
>   File "site-packages/kart-0.9.1.dev0+ci.2314.git8e4ee8c1-py3.7.egg/kart/sqlalchemy/adapter/base.py", line 104, in sql_type_to_v2_type
> ValueError: Unsupported SQL type: NAME
> [4236] Failed to execute script kart_cli

I was searching who has data_type = name and I found about 150 columns / 80 tables, most of them in pg_catalog, and all of them are internal of PG/PostGIS. ( There are some table/views in public, but it was created by PostGIS - geometry_columns, raster_columns, raster_overviews)

Is there any way to just express what schemas we want to version?

**Comment by olsen232** [comment] 2021-06-02 23:35
Thanks for your patience!
It might seem like this importer is completely untested - this is actually not true, but unfortunately it has had heavy use by us internally on a big database that, I now see, shows it kind of works but didn't really test all the corner cases. So, thanks for your patience as I work through some of them.

There is a new build building at master for you again: Now every column type that we don't handle explicitly is imported as text, including UUIDs and NAMEs. 
See https://github.com/koordinates/kart/actions/runs/901009587

There is a way to import every table in a particular schema. After kart init, Run the following:
`kart import postgresql://user:password@localhost/db_master/MYSCHEMA --all-tables`

Kart import is currently under documented sorry, particularly the cutting edge, yet-to-be-released, non-OGR based kart import that you are now testing for us. There is also more than one way of importing a table in a particular schema or schemas, if this is helpful to you:
`kart import postgresql://user:password@localhost/db_master SCHEMA1.TABLE1 SCHEMA2.TABLE2 ...`
`kart import postgresql://user:password@localhost/db_master/MYSCHEMA TABLE1 TABLE2 ...`

**Comment by diogooliveira-dsg** [comment] 2021-06-03 15:59
> Thanks for your patience!
> It might seem like this importer is completely untested - this is actually not true, but unfortunately it has had heavy use by us internally on a big database that, I now see, shows it kind of works but didn't really test all the corner cases. So, thanks for your patience as I work through some of them.

Oh, it's me that have to thank you for your disponibility to reply to my topic and make changes to accommodate my case. I have a personal interest in this subject, versioning spatial data. I can help with some tests if this would help you. I work producing spatial data, with QGIS and Postgres/PostGIS as backend repository, so I have a particular interest in importing from PG and also make the WorkingCopy (WC) in PG too. One of the things that I saw in the system, is that to make the PG WC we have to has/create an empty Schema, maybe this could be not so good for some users. Another thing is that the system needs the spatial_ref_sys table in the public schema, but sometimes this is not the case, and the user can make a new schema for PostGIS (i don't realize why but in my system the default configuration create a new schema for PostGIS and create the spatial_ref_sys table and all the spatial functions there - it's not a big issue, but sometimes the user can receive this error message, and could not use the system)


> There is a new build building at master for you again: Now every column type that we don't handle explicitly is imported as text, including UUIDs and NAMEs.
> See https://github.com/koordinates/kart/actions/runs/901009587

I tried this build, but I received an error message: 

```
 kart init --import postgresql://user:password@localhost/db_test              
 Initialized empty Git repository in /home/user/repo_db_test/.kart/ 
 2021-06-03 12:21:54,056 WARNING kart.sqlalchemy.adapter.base - SQL type UUID not fully supported - importing as text  
 ...
 2021-06-03 12:21:55,969 WARNING kart.sqlalchemy.adapter.base - SQL type NAME not fully supported - importing as text 
 Starting git-fast-import... 
 Traceback (most recent call last): 
   File "kart_cli.py", line 4, in <module> 
    File "site-packages/kart-0.9.1.dev0+ci.2319.git798d8516-py3.7.egg/kart/cli.py", line 334, in entrypoint 
    File "site-packages/click/core.py", line 829, in __call__ 
    File "site-packages/click/core.py", line 782, in main 
    File "site-packages/kart-0.9.1.dev0+ci.2319.git798d8516-py3.7.egg/kart/cli.py", line 158, in invoke 
    File "site-packages/click/core.py", line 1259, in invoke 
    File "site-packages/click/core.py", line 1066, in invoke 
    File "site-packages/click/core.py", line 610, in invoke 
    File "site-packages/click/decorators.py", line 21, in new_func 
    File "site-packages/kart-0.9.1.dev0+ci.2319.git798d8516-py3.7.egg/kart/init.py", line 340, in import_ 
    File "site-packages/kart-0.9.1.dev0+ci.2319.git798d8516-py3.7.egg/kart/fast_import.py", line 292, in fast_import_tables 
    File "site-packages/kart-0.9.1.dev0+ci.2319.git798d8516-py3.7.egg/kart/fast_import.py", line 492, in generate_header 
    File "site-packages/kart-0.9.1.dev0+ci.2319.git798d8516-py3.7.egg/kart/fast_import.py", line 506, in generate_message 
    File "site-packages/kart-0.9.1.dev0+ci.2319.git798d8516-py3.7.egg/kart/pk_generation.py", line 440, in aggregate_import_source_desc 
    File "site-packages/kart-0.9.1.dev0+ci.2319.git798d8516-py3.7.egg/kart/sqlalchemy_import_source.py", line 113, in aggregate_import_source_desc 
  AttributeError: 'PkGeneratingImportSource' object has no attribute 'table' 
 [15380] Failed to execute script kart_cli 
```

> There is a way to import every table in a particular schema. After kart init, Run the following:
> `kart import postgresql://user:password@localhost/db_master/MYSCHEMA --all-tables`
> 
> Kart import is currently under documented sorry, particularly the cutting edge, yet-to-be-released, non-OGR based kart import that you are now testing for us. There is also more than one way of importing a table in a particular schema or schemas, if this is helpful to you:
> `kart import postgresql://user:password@localhost/db_master SCHEMA1.TABLE1 SCHEMA2.TABLE2 ...`
> `kart import postgresql://user:password@localhost/db_master/MYSCHEMA TABLE1 TABLE2 ...`

No problems with the documentation, I understand that sometimes we are in a hurry to do the thing in time, and documentation could be not updated.

I tried import by schema (in 2 ways) and it works very well. Thanks! 

`kart init --import postgresql://user:password@localhost/db_test/data_schema `

and

``` 
kart init 
kart import postgresql://user:password@localhost/db_test/data_schema --all-tables
```

For test purposes, I tried to find what schema was the problem one and I received the same error when trying to import public schema. 
But when importing one by one the tables I could import all of them. I can't think what's the problem with the public.


Is there any way to make WC of specific original PG Schemas in more them one WC Schemas?

**Comment by craigds** [comment] 2021-06-03 23:44
Thanks for the detailed info.

> I received the same error when trying to import public schema.

I think it's trying to import from the postgis-internal views/tables. We need to exclude them from the tables we detect, and only find user-defined tables instead. I just tested this query to do so:

```sql
# SELECT e.extname, ne.nspname AS extschema, c.relname, c.relkind
FROM pg_catalog.pg_extension AS e
    INNER JOIN pg_catalog.pg_depend AS d ON (d.refobjid = e.oid)
    INNER JOIN pg_catalog.pg_class c ON (c.oid = d.objid)
    INNER JOIN pg_catalog.pg_namespace AS ne ON (ne.oid = e.extnamespace)
WHERE d.deptype = 'e'
AND c.relkind IN ('v', 'r');
 extname | extschema |      relname      | relkind
---------+-----------+-------------------+---------
 postgis | public    | spatial_ref_sys   | r
 postgis | public    | geography_columns | v
 postgis | public    | geometry_columns  | v
 postgis | public    | raster_columns    | v
 postgis | public    | raster_overviews  | v
(5 rows)
```

I'll see if I can get that working in kart.


>   AttributeError: 'PkGeneratingImportSource' object has no attribute 'table' 

I can reproduce this with my test database, will work on a fix.

**Comment by craigds** [comment] 2021-06-08 01:36
@diogooliveira-dsg I think this build has all the issues fixed: https://github.com/koordinates/kart/actions/runs/916712786

Do you mind trying it out and letting us know how you get on?

Thanks!

**Comment by diogooliveira-dsg** [comment] 2021-06-08 12:57
I tried the build 2335 and it works without any error message.

I tried with a DB with more than 800k features ( 200k point, 290k lines, and 320k polygons) and it took  371,47s to do the import from PG to PG:
`time kart init --import postgresql://user:password@localhost/db_teste --workingcopy postgresql://user:password@localhost/wc_teste/kart` 

I'll try it more and as soon as I can I'll post here more comments

Thanks

**Comment by diogooliveira-dsg** [comment] 2021-06-08 17:13
> I'll try it more and as soon as I can I'll post here more comments

As I was testing, I tried some flows, and I'm receiving errors when trying to checkout to other branch or previous commits:

```
kart checkout main  
Updating postgresql://user@localhost/wc_kart_v2335/kart ...
Traceback (most recent call last):
  File "kart_cli.py", line 4, in <module>
  File "site-packages/kart-0.9.1.dev0+ci.2335.git136b5fa0-py3.7.egg/kart/cli.py", line 334, in entrypoint
  File "site-packages/click/core.py", line 829, in __call__
  File "site-packages/click/core.py", line 782, in main
  File "site-packages/kart-0.9.1.dev0+ci.2335.git136b5fa0-py3.7.egg/kart/cli.py", line 158, in invoke
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 610, in invoke
  File "site-packages/click/decorators.py", line 21, in new_func
  File "site-packages/kart-0.9.1.dev0+ci.2335.git136b5fa0-py3.7.egg/kart/checkout.py", line 131, in checkout
  File "site-packages/kart-0.9.1.dev0+ci.2335.git136b5fa0-py3.7.egg/kart/checkout.py", line 47, in reset_wc_if_needed
  File "site-packages/kart-0.9.1.dev0+ci.2335.git136b5fa0-py3.7.egg/kart/working_copy/base.py", line 1100, in reset
  File "site-packages/kart-0.9.1.dev0+ci.2335.git136b5fa0-py3.7.egg/kart/working_copy/base.py", line 1136, in _update_table
  File "site-packages/kart-0.9.1.dev0+ci.2335.git136b5fa0-py3.7.egg/kart/working_copy/base.py", line 1151, in _apply_feature_diff
  File "site-packages/kart-0.9.1.dev0+ci.2335.git136b5fa0-py3.7.egg/kart/base_dataset.py", line 96, in feature_tree
KeyError: 'feature/'
[10456] Failed to execute script kart_cli
```
In previous builds, it was working. I tested this sequence a couple of times (create/ checkout new branch, modify one feature, commit, checkout to main branch): always the same error.

**Comment by craigds** [comment] 2021-06-08 21:33
I triaged that a bit and managed to produce the same error.

here's how to (master kart @ 136b5fa096b5d5dec26c63be2403ef2a6e71aad5). Note `whatever` is an empty table with a single integer PK column and no rows

https://gist.github.com/craigds/7314b735aa15a28f7f8f6e84f75fd33f

@olsen232 mind looking into that?

**Comment by olsen232** [comment] 2021-06-09 00:18
Once again, there is now a build which has that particular issue fixed:
https://github.com/koordinates/kart/actions/runs/919976545

Good luck!

**Comment by diogooliveira-dsg** [comment] 2021-06-09 12:48
> Once again, there is now a build which has that particular issue fixed:
> https://github.com/koordinates/kart/actions/runs/919976545

I tried the build 2348 and it works without any error message.

I tested the sequence - init, import from PG to PG, create/checkout new branch, modify one feature, commit, checkout to main branch, merge - and now it works normally.

I'll try it more and when I have more comments I'll post them here

Thanks

**Comment by rcoup** [comment] 2021-06-09 19:47
@diogooliveira-dsg thanks for your patience 😃

**Comment by rcoup** [comment] 2021-06-09 19:48
I'll close this one, feel free to file more issues if you run into problems

**Closed by rcoup** 2021-06-09 19:48 UTC
