### ISSUE TITLE
Kart should check PK fields are actually unique

### ISSUE THREAD

**Issue by craigds** [koordinates/kart#879] opened 2023-06-22 22:27 UTC
**Describe the bug**
If you import a tabular dataset with the `--primary-key` option, it's possible to use a field that isn't actually unique.

Kart doesn't check, and any duplicate rows silently overwrite each other during import.

**To Reproduce**

* `sqlite3 bad-pks.sqlite`
* 
    ```
    create table mydataset (badpk integer, sometext text);
    insert into mydataset (badpk, sometext) values (1, 'text1');
    insert into mydataset (badpk, sometext) values (1, 'text2');
    ```
* `kart init myrepo ; cd myrepo`
* `kart import --primary-key=badpk OGR:../bad-pks.sqlite`
* `kart show -- mydataset:feature`

**Expected behaviour**

An error should be raised since the `badpk` field has two duplicate values

**Output**

The dataset is imported and only one of the features survives

```bash
$ kart show -- mydataset:feature
commit d2439097269d5dccd73aaec4d0fd388e6e9aa669
Author: Craig de Stigter <craig@destigter.nz>
Date:   Fri Jun 23 10:21:11 2023 +1200

    Import from bad-pks.sqlite:mydataset to mydataset/

+++ mydataset:feature:1
+                                    badpk = 1
+                                 sometext = text2
```

**Version Info **
 - OS: macOS 13.4
 - Version: 0.14.0rc2

**Comment by hamishcampbell** [comment] 2023-06-27 14:39
Duplicate of https://github.com/koordinates/kart/issues/307 ?

**Closed** 2023-06-27 20:51 UTC
